import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="flex flex-col w-full">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      </head>
      <body className={inter.className}>
        <NavBar />
        <section>
        {children}
        </section>
      </body>
    </html>
  );
}
